### ISSUE TITLE
How to use OIDC classes 

### ISSUE THREAD

**Issue by mousumi16** [apache/submarine#1034]
Please give a sample code on how to use the newly added OIDC feature in apache submarine.
    claimsMap.put("jti", sysUser.getId());
        // TODO(cdmikechen) By default the simple token is used,
        //  in other cases such as ldap it may need to be returned as an interface
        String token = SimpleLoginConfig.getJwtGenerator().generate(claimsMap);
        
        sysUser.setToken(token);

the above code comment is added with OIDC feature. What does this mean and how the OIDC login is going to work?
where to provide the client id n secret details to connect to Keycloak ?

Please guide on this.

**Comment by cdmikechen** [comment]
@mousumi16 Hi~
After enabled oidc, the rest api can directly add the oidc token into the header, or when logging in, the submarine will automatically jump to the SSO page (such as the login address of keycloak).
Specific design ideas can be found here https://submarine.apache.org/docs/next/designDocs/wip-designs/security-implementation. You need to add the relevant configurations to the submarine server. 
In addition, here is a related test case for reference: https://github.com/apache/submarine/blob/master/submarine-server/server-core/src/test/java/org/apache/submarine/server/security/oidc/SubmarineAuthOidcTest.java

**Comment by cdmikechen** [comment]
We are working on an operator upgrade. After we upgrade operator to v3, you can add this envs to CR to support OIDC:
```yaml
spec:
  server:
    env:
      - name: SUBMARINE_AUTH_TYPE
        value: oidc
      - name: SUBMARINE_AUTH_OIDC_CLIENT_ID
        value: "${YOUR_CLIENT_ID}"
      - name: SUBMARINE_AUTH_OIDC_CLIENT_SECRET
        value: "${YOUR_CLIENT_SECRET}"
      - name: SUBMARINE_AUTH_OIDC_DISCOVER_URI
        value: "${YOUR_DISCOVER_URI}"
```
